name: Deploy Jimta Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 89.58.4.31 > ~/.ssh/known_hosts

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Deploy JAR to Server
        run: |
          JAR_NAME="jimta-0.0.1-SNAPSHOT.jar"
          LOCAL_JAR_PATH="target/$JAR_NAME"
          REMOTE_SERVER="admin@89.58.4.31"
          REMOTE_JAR_DIR="/opt/jimta"

          rsync -avz -e "ssh" $LOCAL_JAR_PATH $REMOTE_SERVER:$REMOTE_JAR_DIR/$JAR_NAME

          ssh $REMOTE_SERVER << EOF
            mv $REMOTE_JAR_DIR/$JAR_NAME $REMOTE_JAR_DIR/jimta.jar
            sudo systemctl restart jimta.service
          EOF